### ISSUE TITLE
CollectionObject Mapper fails on term list vocabulary items and local persons with non-latin characters

### ISSUE THREAD

**Issue by atsakir** [collectionspace/collectionspace-csv-importer#212] opened 2024-05-03 00:11 UTC
Using the collectionobject (core-7-2-0) mappers and trying to import any type of field value that is part of a vocabulary fails, e.g.:

objectNumber | variableMediaComponentStatus | INFO: rownum | INFO: rowoccurrence | INFO: record status | ERR: mapper
-- | -- | -- | -- | -- | --
D168 | exhibition | 2 | 2.1 | existing |  
US25 | exhibition |   |   |   | Mapper did not return result for unexpected reason. Please send a copy of this report to collectionspace@lyrasis.org. We will use the following info to diagnose and fix the problem, but you may ignore it: Tried to parse: 0f9619e3-ae33-4e4b-ab5b -- /usr/local/bundle/bundler/gems/collectionspace-mapper-1c786e91097d/lib/collectionspace/mapper/tools/ref_name.rb:79:in `new_from_urn'
CL18 | archival | 4 | 4.1 | existing |  

The default values for that particular vocabulary haven't been modified through the Term Lists if that makes any difference.

Also trying to import persons with non-Latin names using the Display name value in e.g.  'annotationAuthor' 
fails
![brave_ygHs1B64OT](https://github.com/collectionspace/collectionspace-csv-importer/assets/4006246/2f25c266-934d-4c20-832d-3d0dac80fb0e)

objectNumber | annotationAuthor | ERR: mapper
-- | -- | --
D168 | Another Test | Mapper did not return result for unexpected reason. Please send a copy of this report to collectionspace@lyrasis.org. We will use the following info to diagnose and fix the problem, but you may ignore it: Tried to parse: 260ef322-80e9-48eb-96c7 -- /usr/local/bundle/bundler/gems/collectionspace-mapper-1c786e91097d/lib/collectionspace/mapper/tools/ref_name.rb:79:in `new_from_urn'
US25 | Name Surname | Mapper did not return result for unexpected reason. Please send a copy of this report to collectionspace@lyrasis.org. We will use the following info to diagnose and fix the problem, but you may ignore it: Tried to parse: edbd9c60-249b-4606-8ecd -- /usr/local/bundle/bundler/gems/collectionspace-mapper-1c786e91097d/lib/collectionspace/mapper/tools/ref_name.rb:79:in `new_from_urn'
CL18 | Test | Mapper did not return result for unexpected reason. Please send a copy of this report to collectionspace@lyrasis.org. We will use the following info to diagnose and fix the problem, but you may ignore it: Tried to parse: f13661f9-a65c-47b7-8a9e -- /usr/local/bundle/bundler/gems/collectionspace-mapper-1c786e91097d/lib/collectionspace/mapper/tools/ref_name.rb:79:in `new_from_urn'
D12 | Ηρακλής Γκουντάρας |  
D13 | Όλγα Μούτσιανου |  

If only Latin names are used the mapping  completes successfully:

objectNumber | annotationAuthor | INFO: rownum | INFO: rowoccurrence | INFO: record status
-- | -- | -- | -- | --
D168 | Another Test | 2 | 2.1 | existing
US25 | Name Surname | 3 | 3.1 | existing
CL18 | Test | 4 | 4.1 | existing

Is there a way to include a non-Latin person's Display name field in collectionObject CSVs somehow that I'm missing?

**Comment by kspurgin** [comment] 2024-05-03 19:34
Hi, 

I'm not able to reproduce these problems. I just used https://importer.collectionspace.org with the core-7-2-0 collectionobject mapper to create [this new test record in the Core Demo site](https://core.collectionspace.org/cspace/core/record/collectionobject/78180b63-5197-44c2-8ed0).

[gh212-20240503-1842_processing_report.csv](https://github.com/collectionspace/collectionspace-csv-importer/files/15203965/gh212-20240503-1842_processing_report.csv)
<img width="1125" alt="image" src="https://github.com/collectionspace/collectionspace-csv-importer/assets/450570/0fa8209f-1965-4a84-b00b-dfd16536fb7e">

<img width="1125" alt="image" src="https://github.com/collectionspace/collectionspace-csv-importer/assets/450570/bcb562cb-df7f-4b82-a22c-bab1d4ccbcba">

Without access to your actual CollectionSpace instance, database, CSV Importer instance/logs, etc., it will be virtually impossible for me to troubleshoot/advise on a problem I can't duplicate. 

What I noticed from your examples, if you've copied the info received in the CSV Importer processing reports fully/accurately: 

- In the variableMediaComponentStatus example, the variableMediaComponentStatus values "exhibtion" and "archival" imported fine for object #s D168 and CL18. It only returned an error for the use of "exhibition" in US25. So the problem is not that it errors out whenever a field is populated from a field with a vocabulary 
- In the first annotationAuthor example the errors are on the rows with all-Latin-character names. The non-Latin names appear to have been mapped correctly, as the rows for D12 and D13 do not have error messages. 

One thing striking me as odd in the error messages themselves is the failing code (collectionspace-mapper/tools/ref_name#new_from_urn) expects to receive a CS refname URN to parse. But the error messages make it look like that method is receiving a record CSID/UUID as you see in the record URI/URLs. 

```
<refName>
  urn:cspace:core.collectionspace.org:personauthorities:name(person):item:name(1714761250427)'Ηρακλής Γκουντάρας'
</refName>
<uri>
  /personauthorities/e4c805d1-dbc6-4d86-b925/items/3d2a8cfd-11f6-477b-9e67
</uri>
```
Is the tried-to-parse value "260ef322-80e9-48eb-96c7" associated with the D168 object record, or the Another Test person record? 

This feels like it might be more related to the process of checking the status of the target record, not the translation of the vocabulary term or name into the refname URN required by CollectionSpace.

**Comment by kspurgin** [comment] 2024-05-03 19:49
Also, if you could share your collectionspace-csv-importer Gemfile.lock, that might tell me something. 

I believe the last time I received reports of "Mapper did not return result for unexpected reason" errors related to mapper/tools/refname.rb was in July 2022 and fixed in [this pull request](https://github.com/collectionspace/collectionspace-csv-importer/pull/180).

**Comment by kspurgin** [comment] 2024-05-03 20:27
Digging in a little more, here's a thing to check: make sure you have two different URLs set for REDIS_CSIDCACHE_URL and REDIS_REFCACHE_URL. See the bottom of [the CSV Importer readme](https://github.com/collectionspace/collectionspace-csv-importer) and lines 35 & 41 in [the config/application.rb file](https://github.com/collectionspace/collectionspace-csv-importer/blob/master/config/application.rb)

Make sure nothing in your [environment setup](https://github.com/collectionspace/collectionspace-csv-importer/tree/master/config/environments) is overwriting/messing with this. 

The CSID cache is written to/used for checking the status of records by looking them up by the ID appearing at the end of the record URI.

The REFCACHE is written to when a vocabulary or authority term is looked up, so if a term is used again in your CSV we don't have to make another API call you your instance again to get the term's RefName URN. 

Revisiting the code, the only time that "new_from_urn" method should get called is when the mapper has encountered a term for the first time in a batch and has either (a) retrieved a value for the term from the REFCACHE; or (b) not found the term in REFCACHE and retrieved the term's refname URN via an API call to your instance. This is done as part of keeping track of known unknown terms in a batch for later reporting. 

Values in the caches persist for some time across batches. If you don't have separate URLs for those two caches, some earlier batch may have checked for the existence/status of a term and cached its CSID. Then when you try to _use_ the term, it checks the SAME cache for the term and gets a CSID instead of a refname URN and tries to proceed. 

I think this is the explanation for what you are seeing.

**Comment by atsakir** [comment] 2024-05-05 16:55
Thank you for your help so far, but I don't think it is a cache URL issue. 
I followed the instructions on both the [CSpace 7.0 Confluence page](https://collectionspace.atlassian.net/wiki/spaces/CSPACE70/pages/2715255261/Installing+on+Ubuntu+LTS) and the CSV Importer installation instructions under docker compose in this repository, to the letter with no errors. 

I haven't changed anything from the default docker-compose configuration, not even the  .env.example file. 

docker-compose.yml:

```services:
  importer:
    build:
      context: .
    depends_on:
      - postgres
      - redis
    environment:
      DB_MIGRATE: "true"
    env_file:
      - .env.example
    ports:
      - 3000:3000
    volumes:
      - storage:/usr/app/storage

  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:6
    command: redis-server --loglevel warning
    ports:
      - 6379:6379
    volumes:
      - redis:/data
```

.env.example: 

```
APP_URL=http://localhost:3000
AWS_ACCESS_KEY_ID=""
AWS_BUCKET=""
AWS_REGION=""
AWS_SECRET_ACCESS_KEY=""
CSV_MAX_ROWS=10000
DATABASE_URL=postgres://postgres:password@postgres/importer
LANG=en_US.UTF-8
LOCKBOX_MASTER_KEY=0000000000000000000000000000000000000000000000000000000000000000
RACK_ENV=production
RAILS_ENV=production
RAILS_FORCE_SSL=false
RAILS_LOG_TO_STDOUT=true
RAILS_SERVE_STATIC_FILES=true
RAILS_STORAGE_SERVICE=local
REDIS_URL=redis://redis:6379/0
SECRET_KEY_BASE=123456
```

The application.rb file is unchanged as well:
` config.csidcache_url = ENV.fetch('REDIS_CSIDCACHE_URL') do
      ENV.fetch('REDIS_URL', 'redis://localhost:6379/5')
    end`
`   config.refcache_url = ENV.fetch('REDIS_REFCACHE_URL') do
      ENV.fetch('REDIS_URL', 'redis://localhost:6379/3')
    end
`
as is the environments/production.rb
```  config.cache_store = :redis_cache_store, {
    namespace: 'ccip',
    url: ENV.fetch('REDIS_CACHE_URL') do
      ENV.fetch('REDIS_URL', 'redis://localhost:6379/0')
    end,
    ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE }
  }
  config.session_store :redis_session_store,
                       key: '_importer_session_production',
                       serializer: :json,
                       redis: {
                         expire_after: 1.day,
                         ttl: 1.day,
                         key_prefix: 'ccip:session:',
                         url: ENV.fetch('REDIS_SESSION_URL') do
                                ENV.fetch('REDIS_URL', 'redis://localhost:6379/4')
                              end,
                         ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE }
                       }
```

To rule out any customization I did that may have had an adverse effect on my cspace instance, I even deployed a completely new vanilla instance of CollectionSpace7.2.0 and a new deployment of CSV Importer on a separate Ubuntu 20.04 VM without any changes to default configurations or any data ingress to cspace of any kind. I connected the new instance of CSV Importer to that server with the manifest for 7.2.0 from [here](https://raw.githubusercontent.com/collectionspace/cspace-config-untangler/main/data/mapper_manifests/community_profile_mappers_release_7_2.json), imported all 326 mappers and tried a new batch to import some collectionObject records containing only `objectNumber` and `assignedSignificance` fields (just to test an arbitrary vocabulary item). Same error... after the first time a vocabulary value is found and set as new item, the mapper fails on any subsequent lines containing the same value

[fdgdfg-20240505-1638_processing_report.csv](https://github.com/collectionspace/collectionspace-csv-importer/files/15213738/fdgdfg-20240505-1638_processing_report.csv)

objectNumber | assignedSignificance
-- | --
US25 | essential
CL18 | historical
ΤΒ1 | essential
TT36 | essential
EDU2 | historical

The only thing I haven't done in any of my CollectionSpace deployments since the instructions in the Confluence documentation point to a URL I can only assume is from an earlier version of CollectionSpace is **initialize data** as instructed [here](https://collectionspace.atlassian.net/wiki/spaces/CSPACE70/pages/2715255353/Initializing+data) because there seems to be no path `http://<ip-address>:8180/collectionspace/tenant/core/authorities/initialise`

Is there another step I need to do to initialise authorities and vocabularies under 7.2.0 that I have missed?

**Closed** 2024-05-06 15:43 UTC
